using AutoMapper;
using PP_NominasBack.Dtos.Catalogos.Shared;
using PP_NominasBack.Models.Catalogos;
using PP_NominasBack.Dtos.Catalogos;

namespace PP_NominasBack.Profiles
{
    public class CatalogosProfile : Profile
    {
        public CatalogosProfile()
        {
            CreateMap<Models.Catalogos.Empleados.Empleado, Dtos.Catalogos.Empleados.EmpleadoDto>().ReverseMap();
            CreateMap<Models.Catalogos.Empleados.ContratoEmpleado, Dtos.Catalogos.Empleados.ContratoEmpleadoDto>().ReverseMap();
            CreateMap<Models.Catalogos.Empleados.ArchivoEmpleado, Dtos.Catalogos.Empleados.ArchivoEmpleadoDto>().ReverseMap();
            CreateMap<Models.Catalogos.Empleados.DatosPagoEmpleado, Dtos.Catalogos.Empleados.DatosPagoEmpleadoDto>().ReverseMap();
            CreateMap<Models.Catalogos.Empleados.AsignacionPlazaEmpleado, Dtos.Catalogos.Empleados.AsignacionPlazaEmpleadoDto>().ReverseMap();
            CreateMap<Models.Catalogos.Empleados.HistorialPlazaEmpleado, Dtos.Catalogos.Empleados.HistorialPlazaEmpleadoDto>().ReverseMap();
            CreateMap<Models.Catalogos.Empleados.EmpleadoContacto, Dtos.Catalogos.Empleados.EmpleadoContactoDto>().ReverseMap();
            CreateMap<Models.Catalogos.Empleados.TipoArchivoEmpleado, Dtos.Catalogos.Empleados.TipoArchivoEmpleadoDto>().ReverseMap();
            CreateMap<Models.Catalogos.Organizacion.GrupoEmpresa, Dtos.Catalogos.Organizacion.GrupoEmpresaDto>().ReverseMap();
            CreateMap<Models.Catalogos.Organizacion.Division, Dtos.Catalogos.Organizacion.DivisionDto>().ReverseMap();
            CreateMap<Models.Catalogos.Organizacion.Puesto, Dtos.Catalogos.Organizacion.PuestoDto>().ReverseMap();
            CreateMap<Models.Catalogos.Organizacion.Departamento, Dtos.Catalogos.Organizacion.DepartamentoDto>().ReverseMap();
            CreateMap<Models.Catalogos.Organizacion.Plaza, Dtos.Catalogos.Organizacion.PlazaDto>().ReverseMap();
            CreateMap<Models.Catalogos.Nan.CentroTrabajo, Dtos.Catalogos.Nan.CentroTrabajoDto>().ReverseMap();
            CreateMap<Models.Catalogos.Organizacion.EmpresaCentroTrabajo, Dtos.Catalogos.Organizacion.EmpresaCentroTrabajoDto>().ReverseMap();
            CreateMap<Models.Catalogos.Organizacion.Organigrama, Dtos.Catalogos.Organizacion.OrganigramaDto>().ReverseMap();
            CreateMap<Models.Catalogos.Organizacion.Ubicacion, Dtos.Catalogos.Organizacion.UbicacionDto>().ReverseMap();
            CreateMap<Models.Catalogos.Asistencia.Turno, Dtos.Catalogos.Asistencia.TurnoDto>().ReverseMap();
            CreateMap<Models.Catalogos.Asistencia.PlantillaTurnoDetalle, Dtos.Catalogos.Asistencia.PlantillaTurnoDetalleDto>().ReverseMap();
            CreateMap<Models.Catalogos.Asistencia.HorarioPlantilla, Dtos.Catalogos.Asistencia.HorarioPlantillaDto>().ReverseMap();
            CreateMap<Models.Catalogos.Asistencia.PlantillaMensual, Dtos.Catalogos.Asistencia.PlantillaMensualDto>().ReverseMap();
            CreateMap<Models.Catalogos.Asistencia.Checada, Dtos.Catalogos.Asistencia.ChecadaDto>().ReverseMap();
            CreateMap<Models.Catalogos.Asistencia.ChecadaRemota, Dtos.Catalogos.Asistencia.ChecadaRemotaDto>().ReverseMap();
            CreateMap<Models.Catalogos.Asistencia.ChecadaAgregada, Dtos.Catalogos.Asistencia.ChecadaAgregadaDto>().ReverseMap();
            CreateMap<Models.Catalogos.Asistencia.RangoTolerancia, Dtos.Catalogos.Asistencia.RangoToleranciaDto>().ReverseMap();
            CreateMap<Models.Catalogos.Asistencia.CompensacionOvertime, Dtos.Catalogos.Asistencia.CompensacionOvertimeDto>().ReverseMap();
            CreateMap<Models.Catalogos.Asistencia.CalendarioLaboral, Dtos.Catalogos.Asistencia.CalendarioLaboralDto>().ReverseMap();
            CreateMap<Models.Catalogos.Asistencia.HorarioExcepcion, Dtos.Catalogos.Asistencia.HorarioExcepcionDto>().ReverseMap();
            CreateMap<Models.Catalogos.Incidencias.Incidencia, Dtos.Catalogos.Incidencias.IncidenciaDto>().ReverseMap();
            CreateMap<Models.Catalogos.Incidencias.TipoIncidencia, Dtos.Catalogos.Incidencias.TipoIncidenciaDto>().ReverseMap();
            CreateMap<Models.Catalogos.Incidencias.Justificante, Dtos.Catalogos.Incidencias.JustificanteDto>().ReverseMap();
            CreateMap<Models.Catalogos.Incidencias.HistorialIncidencia, Dtos.Catalogos.Incidencias.HistorialIncidenciaDto>().ReverseMap();
            CreateMap<Models.Catalogos.Incidencias.PreNominaIncidencia, Dtos.Catalogos.Incidencias.PreNominaIncidenciaDto>().ReverseMap();
            CreateMap<Models.Catalogos.Incidencias.IncapacidadMedica, Dtos.Catalogos.Incidencias.IncapacidadMedicaDto>().ReverseMap();
            CreateMap<Models.Catalogos.VacacionesPermisos.Vacaciones, Dtos.Catalogos.VacacionesPermisos.VacacionesDto>().ReverseMap();
            CreateMap<Models.Catalogos.VacacionesPermisos.PeriodoVacacional, Dtos.Catalogos.VacacionesPermisos.PeriodoVacacionalDto>().ReverseMap();
            CreateMap<Models.Catalogos.PrenominaNomina.ConfiguracionNomina, Dtos.Catalogos.PrenominaNomina.ConfiguracionNominaDto>().ReverseMap();
            CreateMap<Models.Catalogos.PrenominaNomina.PeriodoNomina, Dtos.Catalogos.PrenominaNomina.PeriodoNominaDto>().ReverseMap();
            CreateMap<Models.Catalogos.PrenominaNomina.TipoPeriodo, Dtos.Catalogos.PrenominaNomina.TipoPeriodoDto>().ReverseMap();
            CreateMap<Models.Catalogos.PrenominaNomina.ControlCierrePrenomina, Dtos.Catalogos.PrenominaNomina.ControlCierrePrenominaDto>().ReverseMap();
            CreateMap<Models.Catalogos.PrenominaNomina.DetallePercepciones, Dtos.Catalogos.PrenominaNomina.DetallePercepcionesDto>().ReverseMap();
            CreateMap<Models.Catalogos.PrenominaNomina.DetalleDeducciones, Dtos.Catalogos.PrenominaNomina.DetalleDeduccionesDto>().ReverseMap();
            CreateMap<Models.Catalogos.PrenominaNomina.ReciboNomina, Dtos.Catalogos.PrenominaNomina.ReciboNominaDto>().ReverseMap();
            CreateMap<Models.Catalogos.PrenominaNomina.HistorialValidacion, Dtos.Catalogos.PrenominaNomina.HistorialValidacionDto>().ReverseMap();
            CreateMap<Models.Catalogos.PrenominaNomina.CfdiNomina, Dtos.Catalogos.PrenominaNomina.CfdiNominaDto>().ReverseMap();
            CreateMap<Models.Catalogos.ContratosPrestaciones.TipoContrato, Dtos.Catalogos.ContratosPrestaciones.TipoContratoDto>().ReverseMap();
            CreateMap<Models.Catalogos.ContratosPrestaciones.TabuladorSalarial, Dtos.Catalogos.ContratosPrestaciones.TabuladorSalarialDto>().ReverseMap();
            CreateMap<Models.Catalogos.CompensacionesDeducciones.CatalogoCompensaciones, Dtos.Catalogos.CompensacionesDeducciones.CatalogoCompensacionesDto>().ReverseMap();
            CreateMap<Models.Catalogos.CompensacionesDeducciones.CatalogoPrestaciones, Dtos.Catalogos.CompensacionesDeducciones.CatalogoPrestacionesDto>().ReverseMap();
            CreateMap<Models.Catalogos.CompensacionesDeducciones.CatalogoDeducciones, Dtos.Catalogos.CompensacionesDeducciones.CatalogoDeduccionesDto>().ReverseMap();
            CreateMap<Models.Catalogos.CompensacionesDeducciones.FiniquitoLiquidacion, Dtos.Catalogos.CompensacionesDeducciones.FiniquitoLiquidacionDto>().ReverseMap();
            CreateMap<Models.Catalogos.CompensacionesDeducciones.EmpleadoCompensacion, Dtos.Catalogos.CompensacionesDeducciones.EmpleadoCompensacionDto>().ReverseMap();
            CreateMap<Models.Catalogos.CompensacionesDeducciones.EmpleadoDeduccion, Dtos.Catalogos.CompensacionesDeducciones.EmpleadoDeduccionDto>().ReverseMap();
            CreateMap<Models.Catalogos.ControlPago.CentroPagoNomina, Dtos.Catalogos.ControlPago.CentroPagoNominaDto>().ReverseMap();
            CreateMap<Models.Catalogos.ControlPago.ResponsableNomina, Dtos.Catalogos.ControlPago.ResponsableNominaDto>().ReverseMap();
            CreateMap<Models.Catalogos.Fiscal.TablaIsr, Dtos.Catalogos.Fiscal.TablaIsrDto>().ReverseMap();
            CreateMap<Models.Catalogos.Fiscal.TablaImss, Dtos.Catalogos.Fiscal.TablaImssDto>().ReverseMap();
            CreateMap<Models.Catalogos.Fiscal.TablaUma, Dtos.Catalogos.Fiscal.TablaUmaDto>().ReverseMap();
            CreateMap<Models.Catalogos.Fiscal.TablaInfonavit, Dtos.Catalogos.Fiscal.TablaInfonavitDto>().ReverseMap();
            CreateMap<Models.Catalogos.Fiscal.CuotaObreroPatronal, Dtos.Catalogos.Fiscal.CuotaObreroPatronalDto>().ReverseMap();
            CreateMap<Models.Catalogos.FondosAhorro.FondoAhorro, Dtos.Catalogos.FondosAhorro.FondoAhorroDto>().ReverseMap();
            CreateMap<Models.Catalogos.FondosAhorro.MovimientoFondoAhorro, Dtos.Catalogos.FondosAhorro.MovimientoFondoAhorroDto>().ReverseMap();
            CreateMap<Models.Catalogos.Seguridad.Usuario, Dtos.Catalogos.Seguridad.UsuarioDto>().ReverseMap();
            CreateMap<Models.Catalogos.Seguridad.Perfil, Dtos.Catalogos.Seguridad.PerfilDto>().ReverseMap();
            CreateMap<Models.Catalogos.Configuracion.ParametroSistema, Dtos.Catalogos.Configuracion.ParametroSistemaDto>().ReverseMap();
            CreateMap<Models.Catalogos.Configuracion.ConfiguracionGlobal, Dtos.Catalogos.Configuracion.ConfiguracionGlobalDto>().ReverseMap();
            CreateMap<Models.Catalogos.Configuracion.Politica, Dtos.Catalogos.Configuracion.PoliticaDto>().ReverseMap();
            CreateMap<Models.Catalogos.Shared.Auditable, Dtos.Catalogos.Shared.AuditableDto>().ReverseMap();
            CreateMap<Models.Catalogos.Shared.Persona, Dtos.Catalogos.Shared.PersonaDto>().ReverseMap();
            CreateMap<Models.Catalogos.Shared.Telefono, Dtos.Catalogos.Shared.TelefonoDto>().ReverseMap();
            CreateMap<Models.Catalogos.Shared.Direccion, Dtos.Catalogos.Shared.DireccionDto>().ReverseMap();
            CreateMap<Models.Catalogos.Shared.Contacto, Dtos.Catalogos.Shared.ContactoDto>().ReverseMap();
            CreateMap<Models.Catalogos.AlertasValidacionesEnums.FlujoValidacion, Dtos.Catalogos.AlertasValidacionesEnums.FlujoValidacionDto>().ReverseMap();
            CreateMap<Models.Catalogos.AlertasValidacionesEnums.PasoFlujoValidacion, Dtos.Catalogos.AlertasValidacionesEnums.PasoFlujoValidacionDto>().ReverseMap();
            CreateMap<Models.Catalogos.AlertasValidacionesEnums.DestinatarioAlerta, Dtos.Catalogos.AlertasValidacionesEnums.DestinatarioAlertaDto>().ReverseMap();
            CreateMap<Models.Catalogos.AlertasValidacionesEnums.CatalogoEntidades, Dtos.Catalogos.AlertasValidacionesEnums.CatalogoEntidadesDto>().ReverseMap();
            CreateMap<Models.Catalogos.AlertasValidacionesEnums.CatalogoEnums, Dtos.Catalogos.AlertasValidacionesEnums.CatalogoEnumsDto>().ReverseMap();
        }
    }
}